### ISSUE TITLE
Pathfinder-simulation uses "system time"

### ISSUE THREAD

**Issue by MacBlub** [Tugcga/Path-Finder#11]
Hi all,

First: Cool work and pretty useful tbh.

Currently, I am developing a rudimentary simulator, which I need to generate randomized indoor trajectories. So far so good. Everything works as expected, except that the simulator (i.e. here basically the pathfinder object) uses the system time to run a "simulation". 

In itself, this is ok, but I want to generate 1000+ trajectories. If I want to simulate 5min indoor runs this means I have to wait 3.5 days, which could also be simulated much quicker. 

Currently my loop looks like this:
```
for i in range(simulation_time_max):
    positions = pathfinder.get_all_agents_positions()
    # Do stuff
    pathfinder.update()
    time.sleep(1)
```

I had a brief look at the code, and I see some time.time() calls, which could be replaced/adapted with time_delta arguments or a "custom clock"? I forked your project and playing around with it right now, and built a custom package.

Proposed usage-solution with a custom clock:
```
class CustomClock:
    def __init__(self, delta=0.1):
        self.epoch = 1677175385
        self.delta = delta
        self.ct    = 0
    def __call__(self):
        t = self.epoch + self.ct * self.delta
        self.ct += 1
        return t
```

Usage with the Pathfinder system:
`pf.PathFinder(v,p, time_clock=CustomClock(delta=0.1))`

Note, in this case the delta is the change in seconds similar to the unix-epoch standard. 

I am not sure if you are interested in this kind of change/upgrade/feature? But I just want to let you know, I currently have the proposed changes implemented (only changes a few lines). I can share this if requested.

Again: thank you for your cool tool! It helps me a lot for my current project :)

**Comment by Tugcga** [comment]
Some times ago I tried to use pathfinder for some side project, and understand that it is inconvenient. It's too complex and it's hard to control what and when does it do. From this point of view the whole PathFinder class should be considered as an example of using two more elementary submodules: navmesh and rvo2. May be for some tasks it's enough to use only one of these submodules.

So, introducing custom timers is a complication of the module, which is too complex already. In fact any project requires some additional tweaks and custom solutions on the top of the basic module. But it's unnecessary to integrate most of local improvements into this basic module.

In any case, it's great that the module is useful for you and helps to implement your project.

**Comment by MacBlub** [comment]
Ah, ok. No worries. Directly including/playing around with submodules seems a bit overkill for my application right now. I have some other smaller extensions in mind however. So I would include these probably as well. 

To that extend, I am thinking of either creating a fork & package some wheels for my Simulator Project, or directly including some of the files directly in my simulator project. I hope that is okay from your side?

Regarding that: PyPI says your project hat the MIT License, I guess this applies to the code in this repository as well?

Thank you for your very quick response and quick feedback! :)

**Comment by Tugcga** [comment]
I don't fully understand the difference between licenses. And for me the current license does not matter. Of course, you can use any fragment of the code as you like: include to your package, modify, sell, remove, translate into other language. Anything.

**Comment by MacBlub** [comment]
Perfect! Then I will go forward with my plans. Thanks! 

I consider this Issue closed. Thanks again for your answers & feedback! :)
