### ISSUE TITLE
Parsing .obj

### ISSUE THREAD

**Issue by devwar87** [Tugcga/Path-Finder#3]
Hey there, I tried to parse an .obj file that recast is able to open and any 3d model viewer, but failed.

I made some changes to parse the file as the baker_example requires. List of tuples and list of lists but still could not make it work.

Here is the .obj file I am using, the method I used to parse it and the exception, hope you can figure something out.
[PyMethod.txt](https://github.com/Tugcga/Path-Finder/files/8139418/PyMethod.txt)
[3dmodel.zip](https://github.com/Tugcga/Path-Finder/files/8139286/3dmodel.zip)
[PyLog.txt](https://github.com/Tugcga/Path-Finder/files/8139361/PyLog.txt)
![image](https://user-images.githubusercontent.com/72774832/155674456-ad6e3527-c5f7-4912-9de5-baafdb82e53a.png)
![image](https://user-images.githubusercontent.com/72774832/155674708-8fa96230-2545-4902-8df0-499fb3bf1265.png)

Thanks for your work.

**Comment by PrivateCaller** [comment]
I had the same problem, which lead me to trying to load a .BIN file from PyRecastDetour instead. Here's to hoping the maintainer will see these, it's a promising project.

**Comment by Tugcga** [comment]
In the *.obj file the polygon corner indices enumerated from 1. But for the baker the vertices should be enumerated from 0. So, the proper parsing function should be the following:
```
for line in lines:
    if line.startswith('v'):
        vtx = line[2:len(line)].split(" ")
        _tuple = tuple([float(v) for v in vtx])
        print(_tuple)
        vertices_raw.append(_tuple)
    elif line.startswith('f'):
        plgs = line[2:len(line)].split(" ")
        lst = [int(p) - 1 for p in plgs]  # <-- here are changes, add -1
        print(lst)
        triangles_raw.append(lst)
```
After that all works. Baking time is nearly 10 second in my computer. Not very fast, because pure Python in most cases is not very performed.
