### ISSUE TITLE
Generate static file with vertex array, indices array, size array that can be feed into add_geometry as parameters

### ISSUE THREAD

**Issue by issacclee** [Tugcga/Path-Finder#4]
Hi,
I'm not sure if this is the right place to ask this question. @Tugcga 

I found your library through a playcanvas project. [https://playcanv.as/p/MID4JNwZ/](https://playcanv.as/p/MID4JNwZ/).
[https://playcanvas.com/project/869152/overview/path-finder-v2--examples](https://playcanvas.com/project/869152/overview/path-finder-v2--examples)

This project loads vertices, indices and sizes array from a text file
![image](https://user-images.githubusercontent.com/687746/170176818-223c0228-9214-4389-9ac0-d5dfef7c5741.png)

[labyrinth_01.txt](https://github.com/Tugcga/Path-Finder/files/8767821/labyrinth_01.txt)
![image](https://user-images.githubusercontent.com/687746/170176863-2a0c4968-416a-41b1-9d38-963d81964bd7.png)

The creator of this project mentioned that the generation of navmesh(the txt file) was done through some external application. Would you by any chance know what tool is used to generate that text file?

**Comment by Tugcga** [comment]
There are several possibilities to generate navigation mesh:
1. Use the same wasm-module. It contains ```bake``` method, which generate the navigation mesh for input geometry. There is description of the API in the repository. Python version also contains the method to bake navigation mesh, so, you can use it instead wasm one.
2. You can use [this](https://github.com/Tugcga/PyRecastDetour) python module to generate navigation mesh. In fact the algorithm implemented in the wasm-module is the same as in RecastDetour. For demo Playcanvas project I used this Python module for generating txt-presentation of the navigation mesh. 
3. Use Unity to build the scene, generate navmesh and then extract it polygonal description to the text file.
