### ISSUE TITLE
Update AssemblyScript to 0.21.4

### ISSUE THREAD

**Issue by MaxGraey** [Tugcga/Path-Finder#7]
It will be great update AS to recent version and update benchmarks. The last few versions have improved codegen and it would be interesting to see how effective this is in real example. Thanks!

**Comment by Tugcga** [comment]
Previous benchmarks on README page was for 0.21.3 version. I checked results for 0.21.4. Yes, there are small improvements, but they are not very significant. For example, pathfinding time for 147 456 pairs of points changed from 13.21 seconds to 12.85 seconds. Other tasks also increase the performance nearly 2-5%. The size of the compiled modules are not actually changed.

I compile modules with the following options (as example):
```
asc assembly/pathfinder_api.ts assembly/navmesh_api.ts assembly/rvo_api.ts --outFile build/pathfinder.wasm --bindings esm --optimizeLevel 3 --converge --noAssert -Ospeed
```

**Comment by MaxGraey** [comment]
Thanks!
